### ISSUE TITLE
Adding point to itself results in `O`

### ISSUE THREAD

**Issue by mgudemann** [adjoint-io/elliptic-curve#19]
Hi,

thanks a lot for this library!

I followed RFC6090 for the implementation of affine point addition and found that `elliptic-curve` returns `O` in the case of adding a point `p` to itself (at least for Weierstrass curves). I am aware that I can use `dbl` for this, but I wondered why this was chosen that way.

Best regards
Matthias

**Comment by Multramate** [comment]
Hi, thanks for the issue! Point addition should always be via `<>`, which is recorded in:
https://github.com/adjoint-io/elliptic-curve/blob/b0d68d84ac60d7bc1fd8981e8b95c777136a1c72/src/Data/Curve.hs#L178
The functions `add` and `dbl` are meant to be internal functions not to be accessed directly, but are exported in case the user needs them for experimental or some other reason. The function `add` is implemented as such to save a pattern in the overall point addition algorithm in `<>`, since whenever the point x-coordinates are the same in a Weierstrass curve, the y-coordinates would be inverses to each other, and addition would yield `O`.

**Comment by mgudemann** [comment]
Hi @Multramate,

thank you for your answer, this works as I expected.

> since whenever the point x-coordinates are the same in a Weierstrass curve, the y-coordinates would be inverses to each other, and addition would yield `O`.

This is interesting, the RFC states
```
      x3 = ((3*x1^2 + a)/(2*y1))^2 - 2*x1 and
      y3 = (x1-x3)*(3*x1^2 + a)/(2*y1) - y1 if P is equal to Q and y1 is
      not equal to 0.
```
which works for me, i.e., `dbl p` or `p <> p` results in the same point as when I use the above definition for adding the same point to itself. Is this a peculiarity of Weierstrass curves?

**Comment by Multramate** [comment]
Hi, I believe the RFC6090 just rewrites the entire computation into one line, taking into account the various conditions, but the resulting points should be the same. The algorithm for `dbl` is presented from first principles via the standard chord-and-tangent process for elliptic curves, while trying to optimise performance (although I'm not certain the way the code is written makes much of a difference).

**Comment by mgudemann** [comment]
Ok, thank you for your answers!
